# Generated by Django 4.0.6 on 2022-07-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='variaco',
            new_name='variacao',
        ),
    ]
